import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const materials=sqliteTable("materials",{id:text("id").primaryKey(),title:text("title").notNull(),currentVersionId:text("current_version_id"),status:text("status").notNull(),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()});
export const materialVersions=sqliteTable("material_versions",{id:text("id").primaryKey(),materialId:text("material_id").notNull(),versionNumber:integer("version_number").notNull(),documentJson:text("document_json").notNull(),createdAt:text("created_at").notNull()});
export const materialAssets=sqliteTable("material_assets",{id:text("id").primaryKey(),materialVersionId:text("material_version_id").notNull(),assetType:text("asset_type").notNull(),filePath:text("file_path").notNull(),mimeType:text("mime_type").notNull(),width:integer("width"),height:integer("height"),altText:text("alt_text").notNull(),createdAt:text("created_at").notNull()});
export const attempts=sqliteTable("attempts",{id:text("id").primaryKey(),materialVersionId:text("material_version_id").notNull(),learnerName:text("learner_name").notNull(),status:text("status").notNull(),score:real("score"),expAwarded:integer("exp_awarded").notNull().default(0),startedAt:text("started_at").notNull(),completedAt:text("completed_at")});
export const answers=sqliteTable("answers",{id:text("id").primaryKey(),attemptId:text("attempt_id").notNull(),questionId:text("question_id").notNull(),answerText:text("answer_text"),answerJson:text("answer_json"),isCorrect:integer("is_correct",{mode:"boolean"}),createdAt:text("created_at").notNull()});
export const feedback=sqliteTable("feedback",{id:text("id").primaryKey(),attemptId:text("attempt_id").notNull(),questionId:text("question_id"),source:text("source").notNull(),feedbackText:text("feedback_text").notNull(),score:real("score"),createdAt:text("created_at").notNull()});
export const characters=sqliteTable("characters",{id:text("id").primaryKey(),name:text("name").notNull(),stage:text("stage").notNull(),level:integer("level").notNull().default(1),exp:integer("exp").notNull().default(0),designJson:text("design_json").notNull(),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()});
export const characterAssets=sqliteTable("character_assets",{id:text("id").primaryKey(),characterId:text("character_id").notNull(),stage:text("stage").notNull(),filePath:text("file_path").notNull(),createdAt:text("created_at").notNull()});
export const characterHistory=sqliteTable("character_history",{id:text("id").primaryKey(),characterId:text("character_id").notNull(),stage:text("stage").notNull(),level:integer("level").notNull(),exp:integer("exp").notNull(),createdAt:text("created_at").notNull()});
export const activityLogs=sqliteTable("activity_logs",{id:text("id").primaryKey(),action:text("action").notNull(),entityId:text("entity_id"),detailsJson:text("details_json"),createdAt:text("created_at").notNull()});

