import "server-only";
import { materialDocumentSchema, type generationInputSchema } from "@/features/materials/shared/schemas";
import type { MaterialDocument } from "@/features/materials/shared/types";
import { autoGrade } from "@/lib/grading";
import { createAdminClient } from "@/lib/supabase/admin";
import type { z } from "zod";

export type GenerationInput = z.infer<typeof generationInputSchema>;
export type MaterialRow = { id: string; title: string; currentVersionId: string | null; status: string; createdAt: string; updatedAt: string };
export type VersionRow = { id: string; materialId: string; versionNumber: number; documentJson: MaterialDocument; createdAt: string };
export type AttemptRow = { id: string; materialVersionId: string; learnerName: string; status: string; score: number | null; expAwarded: number; startedAt: string; completedAt: string | null };
export type CharacterRow = { id: string; name: string; stage: string; level: number; exp: number; designJson: Record<string, unknown>; createdAt: string; updatedAt: string };

function fail(error: { message: string } | null, operation: string) {
  if (error) throw new Error(`${operation}: ${error.message}`);
}
function material(row: Record<string, unknown>): MaterialRow { return { id: String(row.id), title: String(row.title), currentVersionId: row.current_version_id ? String(row.current_version_id) : null, status: String(row.status), createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
function version(row: Record<string, unknown>): VersionRow { return { id: String(row.id), materialId: String(row.material_id), versionNumber: Number(row.version_number), documentJson: materialDocumentSchema.parse(row.document_json), createdAt: String(row.created_at) }; }
function attempt(row: Record<string, unknown>): AttemptRow { return { id: String(row.id), materialVersionId: String(row.material_version_id), learnerName: String(row.learner_name), status: String(row.status), score: row.score == null ? null : Number(row.score), expAwarded: Number(row.exp_awarded ?? 0), startedAt: String(row.started_at), completedAt: row.completed_at ? String(row.completed_at) : null }; }
function character(row: Record<string, unknown>): CharacterRow { return { id: String(row.id), name: String(row.name), stage: String(row.stage), level: Number(row.level), exp: Number(row.exp), designJson: (row.design_json ?? {}) as Record<string, unknown>, createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }

export function sampleDocument(i: GenerationInput) {
  const pageId = "page-1";
  const qs = Array.from({ length: i.questionCount }, (_, n) => ({ id: `q-${n + 1}`, pageId, order: n + 1, prompt: `${i.unit}について、問題${n + 1}に答えましょう。`, instructions: "考えたことを書いてみましょう。", answerType: i.answerType, choices: i.answerType === "choice" || i.answerType === "multiple-choice" ? [{ id: "a", label: "答えA" }, { id: "b", label: "答えB" }, { id: "c", label: "答えC" }] : undefined, correctAnswer: i.answerType === "number" ? String(n + 1) : i.answerType.includes("choice") ? "a" : "学習内容に沿った答え", explanation: `${i.unit}のポイントを使って考えます。` }));
  return materialDocumentSchema.parse({ version: 1, metadata: { title: `${i.unit} わくわく学習`, grade: i.grade, subject: i.subject, unit: i.unit, objective: `${i.unit}の基本を理解する`, difficulty: i.difficulty, description: i.request || undefined }, presentation: { format: i.format, pageSize: i.pageSize, visualTheme: "明るく安心できる学習空間", colorPalette: ["#4f46e5", "#f59e0b", "#ecfdf5"] }, pages: [{ id: pageId, pageNumber: 1, blocks: [{ id: "title", type: "title", text: `${i.unit} わくわく学習` }, { id: "sub", type: "subtitle", text: `${i.grade}・${i.subject}` }, { id: "point", type: "point", title: "今日のポイント", text: `${i.unit}を自分のペースで楽しく考えよう。` }, ...qs.flatMap(q => [{ id: `block-${q.id}`, type: "question" as const, questionId: q.id }, { id: `field-${q.id}`, type: "answer-field" as const, questionId: q.id }]), { id: "foot", type: "footer-message", text: "最後までよくがんばりました！" }] }], questions: qs, feedbackPolicy: { tone: "gentle", revealAnswer: false, allowHints: true, maxHints: 2 }, accessibility: { highContrast: true, largeText: true, readingSupport: true, imageDescription: `${i.unit}を学ぶ明るい教材背景` } });
}

export async function listMaterials() { const { data, error } = await createAdminClient().from("hub_materials").select("*").order("updated_at", { ascending: false }); fail(error, "教材一覧の取得に失敗しました"); return (data ?? []).map(row => material(row)); }
export async function getMaterial(id: string) { const db = createAdminClient(); const { data: m, error } = await db.from("hub_materials").select("*").eq("id", id).maybeSingle(); fail(error, "教材の取得に失敗しました"); if (!m?.current_version_id) return null; const { data: v, error: versionError } = await db.from("hub_material_versions").select("*").eq("id", m.current_version_id).maybeSingle(); fail(versionError, "教材バージョンの取得に失敗しました"); return v ? { ...material(m), version: version(v), document: materialDocumentSchema.parse(v.document_json) } : null; }
export async function saveMaterial(doc: MaterialDocument, materialId?: string) { const parsed = materialDocumentSchema.parse(doc); const { data, error } = await createAdminClient().rpc("hub_save_material", { p_document: parsed, p_material_id: materialId ?? null }); fail(error, "教材の保存に失敗しました"); return String(data); }
export async function listAttempts() { const { data, error } = await createAdminClient().from("hub_attempts").select("*").order("started_at", { ascending: false }); fail(error, "履歴の取得に失敗しました"); return (data ?? []).map(row => attempt(row)); }
export async function listCharacters() { const { data, error } = await createAdminClient().from("hub_characters").select("*").order("updated_at", { ascending: false }); fail(error, "キャラクターの取得に失敗しました"); return (data ?? []).map(row => character(row)); }
export async function getAttemptHistory() { const rows = await listAttempts(); const ids = [...new Set(rows.map(r => r.materialVersionId))]; if (!ids.length) return rows.map(row => ({ ...row, versionNumber: null as number | null })); const { data, error } = await createAdminClient().from("hub_material_versions").select("id,version_number").in("id", ids); fail(error, "履歴バージョンの取得に失敗しました"); const versions = new Map((data ?? []).map(v => [String(v.id), Number(v.version_number)])); return rows.map(row => ({ ...row, versionNumber: versions.get(row.materialVersionId) ?? null })); }
export async function createAttempt(materialVersionId: string, learnerName: string) { const id = crypto.randomUUID(); const { error } = await createAdminClient().from("hub_attempts").insert({ id, material_version_id: materialVersionId, learner_name: learnerName, status: "in-progress", started_at: new Date().toISOString(), exp_awarded: 0 }); fail(error, "学習開始の保存に失敗しました"); return id; }
export async function saveAnswer(attemptId: string, questionId: string, answerText: string) { const { error } = await createAdminClient().from("hub_answers").upsert({ id: crypto.randomUUID(), attempt_id: attemptId, question_id: questionId, answer_text: answerText, created_at: new Date().toISOString() }, { onConflict: "attempt_id,question_id" }); fail(error, "回答の保存に失敗しました"); }
export async function createCharacter(input: { name: string; design: Record<string, unknown> }) { const id = crypto.randomUUID(), now = new Date().toISOString(); const { error } = await createAdminClient().from("hub_characters").insert({ id, name: input.name, stage: "egg", level: 1, exp: 0, design_json: input.design, created_at: now, updated_at: now }); fail(error, "キャラクターの保存に失敗しました"); return id; }
export async function saveCompletedAttempt(materialId: string, learnerName: string, inputAnswers: Array<{ questionId: string; answer: string }>) { const m = await getMaterial(materialId); if (!m) throw new Error("教材が見つかりません"); const id = crypto.randomUUID(), now = new Date().toISOString(); let correct = 0; const answerRows = [], feedbackRows = []; for (const item of inputAnswers) { const q = m.document.questions.find(x => x.id === item.questionId); if (!q) continue; const ok = autoGrade(q.answerType, item.answer, q.correctAnswer); if (ok) correct++; answerRows.push({ id: crypto.randomUUID(), attempt_id: id, question_id: q.id, answer_text: item.answer, is_correct: ok, created_at: now }); feedbackRows.push({ id: crypto.randomUUID(), attempt_id: id, question_id: q.id, source: "auto", feedback_text: ok ? "正解です。よく考えました！" : "ヒントを使って、もう一度考えてみよう。", score: ok ? 100 : 0, created_at: now }); } const score = Math.round(correct / Math.max(1, m.document.questions.length) * 100); const db = createAdminClient(); const { error } = await db.from("hub_attempts").insert({ id, material_version_id: m.version.id, learner_name: learnerName, status: "completed", score, exp_awarded: 1, started_at: now, completed_at: now }); fail(error, "提出の保存に失敗しました"); if (answerRows.length) { const { error: e } = await db.from("hub_answers").insert(answerRows); fail(e, "回答の保存に失敗しました"); } if (feedbackRows.length) { const { error: e } = await db.from("hub_feedback").insert(feedbackRows); fail(e, "フィードバックの保存に失敗しました"); } const chars = await listCharacters(); const c = chars[0]; if (c) { const exp = c.exp + 20 + correct * 5; const { error: e } = await db.from("hub_characters").update({ exp, level: Math.floor(exp / 100) + 1, stage: exp >= 300 ? "learning-partner" : exp >= 100 ? "child" : "egg", updated_at: now }).eq("id", c.id); fail(e, "成長情報の保存に失敗しました"); } return { id, score, feedback: score === 100 ? "全問正解！すばらしいです。" : "最後までよくがんばりました。間違えた問題を振り返ってみましょう。" }; }
export async function exportHubData() { const db = createAdminClient(); const tables = ["hub_materials", "hub_material_versions", "hub_attempts", "hub_answers", "hub_feedback", "hub_characters"] as const; const output: Record<string, unknown[]> = {}; for (const table of tables) { const { data, error } = await db.from(table).select("*"); fail(error, `${table}のエクスポートに失敗しました`); output[table] = data ?? []; } return { app: "ガクガク教材Hub", version: 2, createdAt: new Date().toISOString(), data: output }; }
