import { desc, eq } from "drizzle-orm"; import { db } from "./db"; import { materials,materialVersions,attempts,answers,feedback,characters } from "./db/schema"; import { materialDocumentSchema,type generationInputSchema } from "@/features/materials/shared/schemas"; import type { z } from "zod";
export type GenerationInput=z.infer<typeof generationInputSchema>;
export function sampleDocument(i:GenerationInput){const pageId="page-1"; const qs=Array.from({length:i.questionCount},(_,n)=>({id:`q-${n+1}`,pageId,order:n+1,prompt:`${i.unit}について、問題 ${n+1} に答えましょう。`,instructions:"考えたことも書いてみよう",answerType:i.answerType,choices:i.answerType==="choice"||i.answerType==="multiple-choice"?[{id:"a",label:"答えA"},{id:"b",label:"答えB"},{id:"c",label:"答えC"}]:undefined,correctAnswer:i.answerType==="number"?String(n+1):i.answerType.includes("choice")?"a":"学習内容に沿った答え",explanation:`${i.unit}のポイントを使って考えます。`})); return materialDocumentSchema.parse({version:1,metadata:{title:`${i.unit} わくわく学習`,grade:i.grade,subject:i.subject,unit:i.unit,objective:`${i.unit}の基本を理解する`,difficulty:i.difficulty,description:i.request||undefined},presentation:{format:i.format,pageSize:i.pageSize,visualTheme:"明るく安心できる学習空間",colorPalette:["#4f46e5","#f59e0b","#ecfdf5"]},pages:[{id:pageId,pageNumber:1,blocks:[{id:"title",type:"title",text:`${i.unit} わくわく学習`},{id:"sub",type:"subtitle",text:`${i.grade}・${i.subject}`},{id:"point",type:"point",title:"今日のポイント",text:`${i.unit}を、順番に楽しく考えよう。`},...qs.flatMap(q=>[{id:`block-${q.id}`,type:"question" as const,questionId:q.id},{id:`field-${q.id}`,type:"answer-field" as const,questionId:q.id}]),{id:"foot",type:"footer-message",text:"最後までよくがんばりました！"}]}],questions:qs,feedbackPolicy:{tone:"gentle",revealAnswer:false,allowHints:true,maxHints:2},accessibility:{highContrast:true,largeText:true,readingSupport:true,imageDescription:`${i.unit}を学ぶ明るい教材背景`}})}
export function listMaterials(){return db.select().from(materials).orderBy(desc(materials.updatedAt)).all()}
export function getMaterial(id:string){const m=db.select().from(materials).where(eq(materials.id,id)).get();if(!m?.currentVersionId)return null;const v=db.select().from(materialVersions).where(eq(materialVersions.id,m.currentVersionId)).get();return v?{...m,version:v,document:materialDocumentSchema.parse(JSON.parse(v.documentJson))}:null}
export function saveMaterial(doc:ReturnType<typeof sampleDocument>,materialId=crypto.randomUUID()){const now=new Date().toISOString(),versionId=crypto.randomUUID();db.transaction(tx=>{tx.insert(materials).values({id:materialId,title:doc.metadata.title,currentVersionId:versionId,status:"published",createdAt:now,updatedAt:now}).onConflictDoUpdate({target:materials.id,set:{title:doc.metadata.title,currentVersionId:versionId,updatedAt:now}}).run();const count=tx.select().from(materialVersions).where(eq(materialVersions.materialId,materialId)).all().length;tx.insert(materialVersions).values({id:versionId,materialId,versionNumber:count+1,documentJson:JSON.stringify(doc),createdAt:now}).run()});return materialId}
export function listAttempts(){return db.select().from(attempts).orderBy(desc(attempts.startedAt)).all()}
export function listCharacters(){return db.select().from(characters).orderBy(desc(characters.updatedAt)).all()}
export {attempts,answers,feedback,characters,materialVersions,db,eq};
